# Generated by Django 3.1.1 on 2020-10-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201009_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='artice_image',
            new_name='article_image',
        ),
    ]
